apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameserver-api
spec:
  selector:
    matchLabels:
      app: gameserver-api
  template:
    metadata:
      labels:
        app: gameserver-api
    spec:
      serviceAccount: admin
      containers:
      - name: gameserver-api
        image: ghcr.io/kondukter-dev/gameserver-api:master
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5000
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-postgresql
              key: postgres-password
        # - name: RABBIT_PASS
        #   valueFrom:
        #     secretKeyRef:
        #       name: rmq-rabbitmq
        #       key: rabbitmq-password
        - name: ENV
          value: dev
        - name: DB_URI
          value: "postgresql+asyncpg://postgres:$(DB_PASS)@db-postgresql.default.svc.cluster.local/postgres"
        # - name: RABBIT_URI
        #   value: "amqp://user:$(RABBIT_PASS)@rmq-rabbitmq.default.svc.cluster.local"
